package com.ice.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ice.greendao.PersonInfo;
import com.ice.greendao.questionResult;

import com.ice.greendao.PersonInfoDao;
import com.ice.greendao.questionResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personInfoDaoConfig;
    private final DaoConfig questionResultDaoConfig;

    private final PersonInfoDao personInfoDao;
    private final questionResultDao questionResultDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personInfoDaoConfig = daoConfigMap.get(PersonInfoDao.class).clone();
        personInfoDaoConfig.initIdentityScope(type);

        questionResultDaoConfig = daoConfigMap.get(questionResultDao.class).clone();
        questionResultDaoConfig.initIdentityScope(type);

        personInfoDao = new PersonInfoDao(personInfoDaoConfig, this);
        questionResultDao = new questionResultDao(questionResultDaoConfig, this);

        registerDao(PersonInfo.class, personInfoDao);
        registerDao(questionResult.class, questionResultDao);
    }

    public void clear() {
        personInfoDaoConfig.getIdentityScope().clear();
        questionResultDaoConfig.getIdentityScope().clear();
    }

    public PersonInfoDao getPersonInfoDao() {
        return personInfoDao;
    }

    public questionResultDao getQuestionResultDao() {
        return questionResultDao;
    }

}
