package com.ice.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ice.greendao.PersonInfo;
import com.ice.greendao.SimpleInfo;
import com.ice.greendao.QuestionResult;

import com.ice.greendao.PersonInfoDao;
import com.ice.greendao.SimpleInfoDao;
import com.ice.greendao.QuestionResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personInfoDaoConfig;
    private final DaoConfig simpleInfoDaoConfig;
    private final DaoConfig questionResultDaoConfig;

    private final PersonInfoDao personInfoDao;
    private final SimpleInfoDao simpleInfoDao;
    private final QuestionResultDao questionResultDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personInfoDaoConfig = daoConfigMap.get(PersonInfoDao.class).clone();
        personInfoDaoConfig.initIdentityScope(type);

        simpleInfoDaoConfig = daoConfigMap.get(SimpleInfoDao.class).clone();
        simpleInfoDaoConfig.initIdentityScope(type);

        questionResultDaoConfig = daoConfigMap.get(QuestionResultDao.class).clone();
        questionResultDaoConfig.initIdentityScope(type);

        personInfoDao = new PersonInfoDao(personInfoDaoConfig, this);
        simpleInfoDao = new SimpleInfoDao(simpleInfoDaoConfig, this);
        questionResultDao = new QuestionResultDao(questionResultDaoConfig, this);

        registerDao(PersonInfo.class, personInfoDao);
        registerDao(SimpleInfo.class, simpleInfoDao);
        registerDao(QuestionResult.class, questionResultDao);
    }
    
    public void clear() {
        personInfoDaoConfig.getIdentityScope().clear();
        simpleInfoDaoConfig.getIdentityScope().clear();
        questionResultDaoConfig.getIdentityScope().clear();
    }

    public PersonInfoDao getPersonInfoDao() {
        return personInfoDao;
    }

    public SimpleInfoDao getSimpleInfoDao() {
        return simpleInfoDao;
    }

    public QuestionResultDao getQuestionResultDao() {
        return questionResultDao;
    }

}
