package com.ice.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON_INFO".
 */
public class PersonInfo {

    private Long id;
    /** Not-null value. */
    private String name;
    private String questionId;
    private String sex;
    private String birthday;
    private String height;
    private String weight;
    private String provider;
    private String relation;
    private String religion;
    private String personId;
    private String education;
    private String occupation;
    private String marriage;
    private String payment;
    private String home;
    private String economy;
    private String oldhelp;
    private String accident;
    private String wish1;
    private String wish2;

    public PersonInfo() {
    }

    public PersonInfo(Long id) {
        this.id = id;
    }

    public PersonInfo(Long id, String name, String questionId, String sex, String birthday, String height, String weight, String provider, String relation, String religion, String personId, String education, String occupation, String marriage, String payment, String home, String economy, String oldhelp, String accident, String wish1, String wish2) {
        this.id = id;
        this.name = name;
        this.questionId = questionId;
        this.sex = sex;
        this.birthday = birthday;
        this.height = height;
        this.weight = weight;
        this.provider = provider;
        this.relation = relation;
        this.religion = religion;
        this.personId = personId;
        this.education = education;
        this.occupation = occupation;
        this.marriage = marriage;
        this.payment = payment;
        this.home = home;
        this.economy = economy;
        this.oldhelp = oldhelp;
        this.accident = accident;
        this.wish1 = wish1;
        this.wish2 = wish2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getQuestionId() {
        return questionId;
    }

    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getRelation() {
        return relation;
    }

    public void setRelation(String relation) {
        this.relation = relation;
    }

    public String getReligion() {
        return religion;
    }

    public void setReligion(String religion) {
        this.religion = religion;
    }

    public String getPersonId() {
        return personId;
    }

    public void setPersonId(String personId) {
        this.personId = personId;
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getOccupation() {
        return occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getMarriage() {
        return marriage;
    }

    public void setMarriage(String marriage) {
        this.marriage = marriage;
    }

    public String getPayment() {
        return payment;
    }

    public void setPayment(String payment) {
        this.payment = payment;
    }

    public String getHome() {
        return home;
    }

    public void setHome(String home) {
        this.home = home;
    }

    public String getEconomy() {
        return economy;
    }

    public void setEconomy(String economy) {
        this.economy = economy;
    }

    public String getOldhelp() {
        return oldhelp;
    }

    public void setOldhelp(String oldhelp) {
        this.oldhelp = oldhelp;
    }

    public String getAccident() {
        return accident;
    }

    public void setAccident(String accident) {
        this.accident = accident;
    }

    public String getWish1() {
        return wish1;
    }

    public void setWish1(String wish1) {
        this.wish1 = wish1;
    }

    public String getWish2() {
        return wish2;
    }

    public void setWish2(String wish2) {
        this.wish2 = wish2;
    }

}
